import { ref } from 'vue'

export const appState = ref({
  conversationType: '',
  callOutcome: '',
  clientReaction: '',
  refusalReason: '',
  refusalConfidence: '',
  nextActionDate: '',
  servicesDiscussed: [],
  summaryNotes: '',
  overallExperience: '',
  clientLikes: [],
  mainReason: '',
  hasConcerns: '',
  primaryConcern: '',
  priceIssue: '',
  competitorName: '',
  estimatedPriceDifference: '',
  competitorPreferenceReason: '',
  locationProblem: '',
  neededState: '',
  neededCity: '',
  suggestedShop: '',
  serviceAvailabilityProblem: '',
  serviceIssue: '',
  relatedService: '',
  shopName: '',
  issueSeverity: '',
  billingIssue: '',
  communicationIssue: '',
  driverIssue: '',
  entityId: '',
  page: 'home'
})
